version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: routine_management
    volumes:
      - ./scripts/setup_db.sql:/docker-entrypoint-initdb.d/setup_db.sql
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db